### ISSUE TITLE
App crashes upon scrolling to bottom of Middle Back workouts

### ISSUE THREAD

**Issue by kctoombs** [kctoombs/FirebaseLogin#2]
When Middle Back workouts are selected and the user scrolls to the bottom of the page, the app crashes. It looks like only 14/15 of the second images are being pulled from the html.
03-15 13:28:12.169 8624-8624/com.example.ktoombs.WorkoutBuddy D/debug: *** Middle Back
03-15 13:28:12.174 8624-8646/com.example.ktoombs.WorkoutBuddy V/FA: Using measurement service
03-15 13:28:12.174 8624-8646/com.example.ktoombs.WorkoutBuddy V/FA: Connection attempt already in progress
03-15 13:28:12.174 8624-8646/com.example.ktoombs.WorkoutBuddy V/FA: Activity resumed, time: 520720921
03-15 13:28:12.176 8624-8661/com.example.ktoombs.WorkoutBuddy D/debug: *** doInBackground ***
03-15 13:28:12.182 8624-8646/com.example.ktoombs.WorkoutBuddy D/FA: Connected to remote service
03-15 13:28:12.182 8624-8646/com.example.ktoombs.WorkoutBuddy V/FA: Processing queued up service tasks: 3
03-15 13:28:12.273 8624-8648/com.example.ktoombs.WorkoutBuddy D/OpenGLRenderer: endAllStagingAnimators on 0xb7337270 (ListView) with handle 0xb746e418
03-15 13:28:12.788 8624-8661/com.example.ktoombs.WorkoutBuddy D/debug: ***ExResult-row ***
03-15 13:28:12.790 8624-8661/com.example.ktoombs.WorkoutBuddy D/debug: *** Workout: T-Bar Row with Handle
03-15 13:28:12.790 8624-8661/com.example.ktoombs.WorkoutBuddy D/debug: *** URL: https://www.bodybuilding.com/exercises/exerciseImages/sequences/1931/Male/m/1931_1.jpg
03-15 13:28:12.818 8624-8661/com.example.ktoombs.WorkoutBuddy D/debug: *** URL: https://www.bodybuilding.com/exercises/exerciseImages/sequences/1931/Male/m/1931_2.jpg
03-15 13:28:12.838 8624-8661/com.example.ktoombs.WorkoutBuddy D/debug: ***ExResult-row ***
03-15 13:28:12.840 8624-8661/com.example.ktoombs.WorkoutBuddy D/debug: *** Workout: Reverse Grip Bent-Over Rows
03-15 13:28:12.841 8624-8661/com.example.ktoombs.WorkoutBuddy W/System.err: java.net.MalformedURLException: Protocol not found: 
03-15 13:28:12.841 8624-8661/com.example.ktoombs.WorkoutBuddy W/System.err:     at java.net.URL.<init>(URL.java:176)
03-15 13:28:12.841 8624-8661/com.example.ktoombs.WorkoutBuddy W/System.err:     at java.net.URL.<init>(URL.java:125)
03-15 13:28:12.841 8624-8661/com.example.ktoombs.WorkoutBuddy W/System.err:     at com.example.ktoombs.WorkoutBuddy.Scraper.parse(Scraper.java:73)
03-15 13:28:12.841 8624-8661/com.example.ktoombs.WorkoutBuddy W/System.err:     at com.example.ktoombs.WorkoutBuddy.WorkoutsActivity$parseTask.doInBackground(WorkoutsActivity.java:101)
03-15 13:28:12.841 8624-8661/com.example.ktoombs.WorkoutBuddy W/System.err:     at com.example.ktoombs.WorkoutBuddy.WorkoutsActivity$parseTask.doInBackground(WorkoutsActivity.java:96)
03-15 13:28:12.841 8624-8661/com.example.ktoombs.WorkoutBuddy W/System.err:     at android.os.AsyncTask$2.call(AsyncTask.java:292)
03-15 13:28:12.841 8624-8661/com.example.ktoombs.WorkoutBuddy W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
03-15 13:28:12.841 8624-8661/com.example.ktoombs.WorkoutBuddy W/System.err:     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
03-15 13:28:12.842 8624-8661/com.example.ktoombs.WorkoutBuddy W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
03-15 13:28:12.842 8624-8661/com.example.ktoombs.WorkoutBuddy W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
03-15 13:28:12.842 8624-8661/com.example.ktoombs.WorkoutBuddy W/System.err:     at java.lang.Thread.run(Thread.java:818)
03-15 13:28:12.842 8624-8661/com.example.ktoombs.WorkoutBuddy D/debug: *** URL: https://www.bodybuilding.com/exercises/exerciseImages/sequences/128/Male/m/128_2.jpg
03-15 13:28:12.911 8624-8661/com.example.ktoombs.WorkoutBuddy D/debug: ***ExResult-row ***
03-15 13:28:12.912 8624-8661/com.example.ktoombs.WorkoutBuddy D/debug: *** Workout: One-Arm Long Bar Row
03-15 13:28:12.912 8624-8661/com.example.ktoombs.WorkoutBuddy D/debug: *** URL: https://www.bodybuilding.com/exercises/exerciseImages/sequences/1941/Male/m/1941_1.jpg
03-15 13:28:12.961 8624-8661/com.example.ktoombs.WorkoutBuddy D/debug: *** URL: https://www.bodybuilding.com/exercises/exerciseImages/sequences/1941/Male/m/1941_2.jpg
03-15 13:28:12.989 8624-8661/com.example.ktoombs.WorkoutBuddy D/debug: ***ExResult-row ***
03-15 13:28:12.990 8624-8661/com.example.ktoombs.WorkoutBuddy D/debug: *** Workout: One-Arm Dumbbell Row
03-15 13:28:12.991 8624-8661/com.example.ktoombs.WorkoutBuddy D/debug: *** URL: https://www.bodybuilding.com/exercises/exerciseImages/sequences/13/Male/m/13_1.jpg
03-15 13:28:13.025 8624-8661/com.example.ktoombs.WorkoutBuddy D/debug: *** URL: https://www.bodybuilding.com/exercises/exerciseImages/sequences/13/Male/m/13_2.jpg
03-15 13:28:13.052 8624-8661/com.example.ktoombs.WorkoutBuddy D/debug: ***ExResult-row ***
03-15 13:28:13.053 8624-8661/com.example.ktoombs.WorkoutBuddy D/debug: *** Workout: Bent Over One-Arm Long Bar Row
03-15 13:28:13.054 8624-8661/com.example.ktoombs.WorkoutBuddy D/debug: *** URL: https://www.bodybuilding.com/exercises/exerciseImages/sequences/19/Male/m/19_1.jpg
03-15 13:28:13.085 8624-8661/com.example.ktoombs.WorkoutBuddy D/debug: *** URL: https://www.bodybuilding.com/exercises/exerciseImages/sequences/19/Male/m/19_2.jpg
03-15 13:28:13.109 8624-8661/com.example.ktoombs.WorkoutBuddy D/debug: ***ExResult-row ***
03-15 13:28:13.111 8624-8661/com.example.ktoombs.WorkoutBuddy D/debug: *** Workout: T-Bar Row
03-15 13:28:13.111 8624-8661/com.example.ktoombs.WorkoutBuddy D/debug: *** URL: https://www.bodybuilding.com/exercises/exerciseImages/sequences/3381/Male/m/3381_1.jpg
03-15 13:28:13.136 8624-8661/com.example.ktoombs.WorkoutBuddy D/debug: *** URL: https://www.bodybuilding.com/exercises/exerciseImages/sequences/3381/Male/m/3381_2.jpg
03-15 13:28:13.175 8624-8661/com.example.ktoombs.WorkoutBuddy D/debug: ***ExResult-row ***
03-15 13:28:13.176 8624-8661/com.example.ktoombs.WorkoutBuddy D/debug: *** Workout: Bent Over Two-Arm Long Bar Row
03-15 13:28:13.176 8624-8661/com.example.ktoombs.WorkoutBuddy D/debug: *** URL: https://www.bodybuilding.com/exercises/exerciseImages/sequences/18/Male/m/18_1.jpg
03-15 13:28:13.224 8624-8661/com.example.ktoombs.WorkoutBuddy D/debug: *** URL: https://www.bodybuilding.com/exercises/exerciseImages/sequences/18/Male/m/18_2.jpg
03-15 13:28:13.245 8624-8661/com.example.ktoombs.WorkoutBuddy D/debug: ***ExResult-row ***
03-15 13:28:13.246 8624-8661/com.example.ktoombs.WorkoutBuddy D/debug: *** Workout: Dumbbell Incline Row
03-15 13:28:13.247 8624-8661/com.example.ktoombs.WorkoutBuddy D/debug: *** URL: https://www.bodybuilding.com/exercises/exerciseImages/sequences/1311/Male/m/1311_1.jpg
03-15 13:28:13.353 8624-8661/com.example.ktoombs.WorkoutBuddy D/debug: *** URL: https://www.bodybuilding.com/exercises/exerciseImages/sequences/1311/Male/m/1311_2.jpg
03-15 13:28:13.394 8624-8661/com.example.ktoombs.WorkoutBuddy D/debug: ***ExResult-row ***
03-15 13:28:13.395 8624-8661/com.example.ktoombs.WorkoutBuddy D/debug: *** Workout: Bodyweight Mid Row
03-15 13:28:13.396 8624-8661/com.example.ktoombs.WorkoutBuddy D/debug: *** URL: https://www.bodybuilding.com/exercises/exerciseImages/sequences/1911/Male/m/1911_1.jpg
03-15 13:28:13.415 8624-8661/com.example.ktoombs.WorkoutBuddy D/debug: *** URL: https://www.bodybuilding.com/exercises/exerciseImages/sequences/1911/Male/m/1911_2.jpg
03-15 13:28:13.433 8624-8661/com.example.ktoombs.WorkoutBuddy D/debug: ***ExResult-row ***
03-15 13:28:13.435 8624-8661/com.example.ktoombs.WorkoutBuddy D/debug: *** Workout: Bent Over Two-Dumbbell Row With Palms In
03-15 13:28:13.435 8624-8661/com.example.ktoombs.WorkoutBuddy D/debug: *** URL: https://www.bodybuilding.com/exercises/exerciseImages/sequences/17/Male/m/17_1.jpg
03-15 13:28:13.456 8624-8661/com.example.ktoombs.WorkoutBuddy D/debug: *** URL: https://www.bodybuilding.com/exercises/exerciseImages/sequences/17/Male/m/17_2.jpg
03-15 13:28:13.486 8624-8661/com.example.ktoombs.WorkoutBuddy D/debug: ***ExResult-row ***
03-15 13:28:13.489 8624-8661/com.example.ktoombs.WorkoutBuddy D/debug: *** Workout: Seated Cable Rows
03-15 13:28:13.490 8624-8661/com.example.ktoombs.WorkoutBuddy D/debug: *** URL: https://www.bodybuilding.com/exercises/exerciseImages/sequences/45/Male/m/45_1.jpg
03-15 13:28:13.515 8624-8661/com.example.ktoombs.WorkoutBuddy D/debug: *** URL: https://www.bodybuilding.com/exercises/exerciseImages/sequences/45/Male/m/45_2.jpg
03-15 13:28:13.534 8624-8661/com.example.ktoombs.WorkoutBuddy D/debug: ***ExResult-row ***
03-15 13:28:13.535 8624-8661/com.example.ktoombs.WorkoutBuddy D/debug: *** Workout: Bent Over Barbell Row
03-15 13:28:13.536 8624-8661/com.example.ktoombs.WorkoutBuddy D/debug: *** URL: https://www.bodybuilding.com/exercises/exerciseImages/sequences/20/Male/m/20_1.jpg
03-15 13:28:13.569 8624-8661/com.example.ktoombs.WorkoutBuddy D/debug: *** URL: https://www.bodybuilding.com/exercises/exerciseImages/sequences/20/Male/m/20_2.jpg
03-15 13:28:13.589 8624-8661/com.example.ktoombs.WorkoutBuddy D/debug: ***ExResult-row ***
03-15 13:28:13.590 8624-8661/com.example.ktoombs.WorkoutBuddy D/debug: *** Workout: Alternating Renegade Row
03-15 13:28:13.591 8624-8661/com.example.ktoombs.WorkoutBuddy D/debug: *** URL: https://www.bodybuilding.com/exercises/exerciseImages/sequences/506/Male/m/506_1.jpg
03-15 13:28:13.608 8624-8661/com.example.ktoombs.WorkoutBuddy D/debug: *** URL: https://www.bodybuilding.com/exercises/exerciseImages/sequences/506/Male/m/506_2.jpg
03-15 13:28:13.625 8624-8661/com.example.ktoombs.WorkoutBuddy D/debug: ***ExResult-row ***
03-15 13:28:13.627 8624-8661/com.example.ktoombs.WorkoutBuddy D/debug: *** Workout: Seated One-arm Cable Pulley Rows
03-15 13:28:13.627 8624-8661/com.example.ktoombs.WorkoutBuddy D/debug: *** URL: https://www.bodybuilding.com/exercises/exerciseImages/sequences/297/Male/m/297_1.jpg
03-15 13:28:13.664 8624-8661/com.example.ktoombs.WorkoutBuddy D/debug: *** URL: https://www.bodybuilding.com/exercises/exerciseImages/sequences/297/Male/m/297_2.jpg
03-15 13:28:13.685 8624-8661/com.example.ktoombs.WorkoutBuddy D/debug: ***ExResult-row ***
03-15 13:28:13.687 8624-8661/com.example.ktoombs.WorkoutBuddy D/debug: *** Workout: Man Maker
03-15 13:28:13.687 8624-8661/com.example.ktoombs.WorkoutBuddy D/debug: *** URL: https://www.bodybuilding.com/exercises/exerciseImages/sequences/4171/Male/m/4171_1.jpg
03-15 13:28:13.707 8624-8661/com.example.ktoombs.WorkoutBuddy D/debug: *** URL: https://www.bodybuilding.com/exercises/exerciseImages/sequences/4171/Male/m/4171_2.jpg
03-15 13:28:13.737 8624-8661/com.example.ktoombs.WorkoutBuddy D/debug: *** firstImages size: 15
03-15 13:28:13.737 8624-8661/com.example.ktoombs.WorkoutBuddy D/debug: *** secondImages size: 14
03-15 13:28:13.739 8624-8624/com.example.ktoombs.WorkoutBuddy D/debug: *** onPostExecute ***
03-15 13:28:16.435 8624-8642/com.example.ktoombs.WorkoutBuddy W/DynamiteModule: Local module descriptor class for com.google.firebase.auth not found.
03-15 13:28:16.982 8624-8624/com.example.ktoombs.WorkoutBuddy D/AndroidRuntime: Shutting down VM
03-15 13:28:16.987 8624-8624/com.example.ktoombs.WorkoutBuddy E/AndroidRuntime: FATAL EXCEPTION: main
Process: com.example.ktoombs.WorkoutBuddy, PID: 8624
java.lang.IndexOutOfBoundsException: Invalid index 14, size is 14
at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
at java.util.ArrayList.get(ArrayList.java:308)
at com.example.ktoombs.WorkoutBuddy.CustomListAdapter.getView(CustomListAdapter.java:87)
at android.widget.AbsListView.obtainView(AbsListView.java:2347)
at android.widget.ListView.makeAndAddView(ListView.java:1864)
at android.widget.ListView.fillDown(ListView.java:698)
at android.widget.ListView.fillGap(ListView.java:662)
at android.widget.AbsListView.trackMotionScroll(AbsListView.java:4991)
at android.widget.AbsListView$FlingRunnable.run(AbsListView.java:4539)
at android.view.Choreographer$CallbackRecord.run(Choreographer.java:767)
at android.view.Choreographer.doCallbacks(Choreographer.java:580)
at android.view.Choreographer.doFrame(Choreographer.java:549)
at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753)
at android.os.Handler.handleCallback(Handler.java:739)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:135)
at android.app.ActivityThread.main(ActivityThread.java:5343)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:905)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:700)

**Comment by kctoombs** [comment]
After going to the website, it appears that the first image for Reverse Grip Bent-Over Rows is blank. The URL for the photo is https://artifacts.bbcomcdn.com/exercises-app/1.0.9/img/1.png
